[platformio]
src_dir = esp32/src
include_dir = esp32/src

[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200

board_build.f_cpu = 240000000L
board_build.partitions = default.csv
platform_packages = platformio/framework-arduinoespressif32@3.20017.241212+sha.dcc1105b

build_flags =
    -D CONFIG_ARDUINO_LOOP_STACK_SIZE=8192
    -D CORE_DEBUG_LEVEL=0

lib_deps =
    dlloydev/QuickPID @ ^3.1.9
    knolleary/PubSubClient@^2.8
    paulstoffregen/OneWire@^2.3.8
    milesburton/DallasTemperature@^3.11.0
    4-20ma/ModbusMaster@^2.0.1